### ISSUE TITLE
Include page title variable in exception templates

### ISSUE THREAD

**Issue by eawoods** [cul-it/arxiv-base#26]
@erickpeirson is this easy to do? Would like to fill our "{{ pagetitle }} | arxiv " titles for all exception pages. It's a tiny thing but would be good for a11y and other reasons.
If very easy, piggyback on my task/ARXIVNG-314 branch, or provide guidance on how to do it?

**Comment by erickpeirson** [comment]
This looks like a quick fix, let me take a quick look...
